site_name: Cellery.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob/master/
edit_uri: website/main-pages/docs/
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2019 WSO2, Inc.
pages:
- Home : 'index.md'
- Philosophy : 'philosophy.md'
- Downloads : 'downloads.md'
- Downloads :
    - Archived : 'downloads/archived.md'
- 404 : 'page-not-found.md'

theme: null
theme_dir: cellery.io-website-theme

