site_name: Ballerina.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob/master/
edit_uri: website/two-column-pages/docs/
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Learn: 'learn.md'
- Community: 'community.md'
- Help: 'help.md'
theme: null
theme_dir: cellery.io-two-col-theme
plugins: []
# extra :
#     base_download_url : 'https://product-dist.ballerina.io/downloads'
#     archived_versions_json : 'https://product-dist.ballerina.io/downloads/archived_releases.json'
#     archived_release_note_html : 'RELEASE_NOTE.html'
#     nightly_versions_json : 'https://product-dist.ballerina.io/downloads/nightly_release.json'
#     latest_versions_json : 'https://product-dist.ballerina.io/downloads/latest_release.json'
